swagger: "2.0"
info:
  title: Linetboot API
  description: Linetboot API for geting host information.
  version: 1.0.0
host: localhost
basePath: /
schemes:
  - http
paths:
  /list:
    get:
      summary: List hosts
      description: List hosts with properties used in host info tabs (props for frontend GUI are in short non-ansible names)
      produces:
        - application/json
      responses:
        200:
          description: Hosts in Array of Objects
          schema:
            type: array
            items:
              $ref: '#/definitions/Host'
  /anslist/play:
    get:
      summary: List Playbooks
      description: List Ansible Playbooks registered in Linetboot playbook paths
      produces:
        - application/json
      responses:
        200:
          description: List of Playbooks in Array of Object
  /rf/info/$hname:
    get:
      summary: Redfish Info
      description: Allows inquiring RedFish Info for Host by host IP Address (w/o knowing BMC address directly)
      produces:
        - application/json
      responses:
        200:
          description: Respond with RedFish host info Object
  /rf/boot/$hname:
    get:
      summary: Execute Booting a Host
      description: Execute immediate boot of host using BMC and possibly boot using method (e.g. PXE) set earlier.
      produces:
        - application/json
      responses:
        200:
          description: Respond with Boot Acknowledgement
  /install_boot?hname=$hname&bootlbl=$bootlbl:
    get:
      summary: Request Booting Host (hname) with PXE by a "Boot Label" (bootlbl)
      description: Request Booting a Host and store the boot label it should boot to. Use a separate call to *actually* boot it.
      produces:
        - application/json
      responses:
        200:
          description: Respond with Boot Acknowledgement
  /bootreset?macaddr=$macaddr:
    get:
      summary: Reset a stored "Boot Label" for a host
      description: Request a host (by explicitly passed MAC address or auto-detected client IP address) to be reset to default boot (boot menu) instead of "Boot Label" it was given earlier.
      produces:
        - application/json
      responses:
        200:
          description: Standard Response. Return MAC file listing on success (e.g. for Client to refresh/redraw listing).
  /installevent/$evtype:
    get:
      summary: Signal a "milestone" event during OS install
      description: Supported events "start" - beginning of install (Install pre-script), "end" - end of install (Install post-script)
      produces:
        - application/json
      responses:
        200:
          description: Simple standard response
definitions:
  Host:
    properties:
      hname:
        type: string
      cores:
        type: integer
