# Ansible
- name: Test A
  hosts: '{{ host }}'
  vars:
    foo: 1
  become: yes
  tasks:
    - name: List
      shell: ls -al /root
      register: rootlist
    - debug: msg='Root listing {{ rootlist.stdout }}'
    - name: Use Identity
      shell: 'echo $USER'
      register: echouser
    - debug: msg='User is {{ echouser.stdout }}'
