# Ansible
- name: Test B
  hosts: '{{ host }}'
  vars:
    foo: 1
  become: yes
  tasks:
    - name: List
      shell: ls -al /tmp
      register: rootlist
    - debug: msg='Root listing {{ rootlist.stdout }}'
