# # Update Dell servers
# 
# ansible-playbook  -i ./hosts dellupdate.yaml -e "ansible_user=... ansible_sudo_pass=... nfsserv=..."
# 
# Assumes certain convention at the NFS server side. If this is hard to achieve in you system,
# edit as needed. Also assumes /mnt is free to use for mounting on the update host.
# Consider using Ansible -e @updparams.json syntax with template:
#   {"nfsserv": "myserv", "mntpt": "/mnt", "fwfname": ""}
- name: Mount Update Binaries Dirs and Run Update
  become: yes
  hosts: '{{ host }}'
  vars:
    nfsserv: 'linetboot.my.com'
    mntpt: "/mnt"
    # R620: iDRAC-with-Lifecycle-Controller_Firmware_0GHF4_LN_2.65.65.65_A00.BIN
    # R630: iDRAC-with-Lifecycle-Controller_Firmware_DNH17_LN_2.70.70.70_A00.BIN
    # M640 and R640
    fwfname: iDRAC-with-Lifecycle-Controller_Firmware_369M3_LN_4.20.20.20_A00.BIN
    biosfname: BIOS_51CVR_LN_2.6.3.BIN
  tasks:
    - name: Mount Update Media from NFS
      shell: 'mount {{ nfsserv }}:/isomnt/dell_r640 {{ mntpt }}'
    - name: Run BIOS Updater Binary
      shell: '{{ mntpt }}/repository/{{ biosfname }} -q -n'
    - name: Run iDRAC Updater Binary
      shell: '{{ mntpt }}/repository/{{ fwfname }} -q -n'
    - name: Unmount temporary mount
      shell: 'umount {{ mntpt }}'
