# ## Install Docker on 
# Example of running:
# ansible-playbook docker_install.yaml -e "dockeruser=misterx"
- name: Install Docker
  hosts: '{{ host }}'
  become: yes
  vars:
    dockeruser: jsmith
    # Seems to be universal (at least in RH, Debian families)
    dockergroup: docker
  tasks:
    - name: Install Docker
      shell:  yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      when: 'ansible_os_family == "RedHat"'
    - name: Add user to a group
      user:
        append: true
        groups: '{{ dockergroup }}'
    - name: Enable docker
      shell: systemctl enable docker
