# ## Collect packages from hosts
# 
# Override destination path from command line
# ```
# ansible-playbook ... -e "destpath=$HOME/hostpkginfo"
# ```
- name: Collect Package List/Metainfo from Hosts
  become: yes
  hosts: '{{ host }}'
  vars:
    destpath: '/tmp/hostpkginfo'
    #NOT: ansible_python_interpreter: '/usr/local/bin/python3'
    # Lookup table for distro associated package listing commands
    cmds:
      Debian: 'dpkg --get-selections'
      RedHat: 'yum list installed'
  #gather_facts: True # Must gather because ansible_os_family
  # fact_path: /etc/ansible/facts.d
  tasks:
    #- name: Get package list (DEB)
    #  shell: 'dpkg --get-selections'
    #  register: pkginfo_d
    #  when: ansible_os_family == "Debian"
    #- name: Get package list (RPM)
    #  shell: 'yum list installed'
    #  register: pkginfo_r
    #  when: ansible_os_family == "RedHat"
    - name: Get package list (RPM/DEB)
      shell: '{{ cmds[ansible_os_family] }}'
      register: pkginfo
    # pkginfo.stdout
    #- debug: var=pkginfo
    - set_fact:
        pkglist: '{{ pkginfo.stdout }}'
    #- debug: var=pkglist
    - name: Save Package list to a file
      become: false
      local_action:
        module: copy
        #content: '{{ pkginfo.stdout }}'
        content: '{{ pkglist }}'
        dest: '{{ destpath }}/{{ inventory_hostname }}'
        #dest: './{{ inventory_hostname }}.tmp.txt'
      #run_once: True
      #delegate_to: localhost
      #delegate_to: 127.0.0.1
