- name: Extract Remote Management (IPMI) Info
  hosts: {{ host }}
  vars:
    homedir: '{{ lookup("env","HOME") }}'
    destpath: '{{ lookup("env","HOME") }}/hostrmgmt'
  become: yes
  tasks:
    # Depends on ipmitool
    - name: Extract iDRAC network Info
      shell: ipmitool lan print 1
      register: laninfo
      ignore_errors: True
      #output: json
    - name: Extract User info
      shell: ipmitool user list 1
      register: userinfo
    - debug: msg="Info {{ laninfo }} "
    # delegate_facts: True
    # Note: Luckily these seem to save only if the content.length > 0
    - name: localhost delegated copy
      copy:
        content: '{{ laninfo.stdout }}'
        dest: '{{ destpath }}/{{ ansible_fqdn }}.lan.txt'
      delegate_to: localhost
      become: no
    - name: localhost delegated copy
      copy:
        content: '{{ userinfo.stdout }}'
        dest: '{{ destpath }}/{{ ansible_fqdn }}.users.txt'
      delegate_to: localhost
      become: no
