# ## Upgrade RedHat Satellite (6.x) on RHEL 8 (minor or patch)
#
# Start by planning the version to update / upgrade to (See section "Versions available" below).
# Example run for patch version (Example scenarios: patch (by pattern): 6.11.z, minor upgrade to exact version 6.12:
# ```
# # Patch upgrade ("update")
# ansible-playbook rhsatupgrade.yaml -l rhsatellite-01.corp.com -e "host=all rhsat_host=rhsatellite-01.corp.com tgtver=6.11.z" --syntax-check
# # Minor upgrade ("upgrade")
# ansible-playbook rhsatupgrade.yaml -l rhsatellite-01.corp.com -e "host=all rhsat_host=rhsatellite-01.corp.com tgtver=6.12 minorup=1" --syntax-check
# Minor upgrade with explicit passing of repos (MUST use JSON params)
# ansible-playbook rhsatupgrade.yaml -l rhsatellite-01.corp.com -e '{"host":"all", "rhsat_host":"rhsatellite-01.corp.com", "tgtver": "6.12", \
#     "minorup": 1, "minorup_repos": ["satellite-maintenance-6.12-for-rhel-8-x86_64-rpms", "satellite-6.12-for-rhel-8-x86_64-rpms"]}'
# ```
# Note: Larger version upgrades within the 6.X version family (e.g. stepping X from 11 to 13) need minorup set to true.
# 
# 
# ## Detecting/Extracting version number pattern
# 
# The version passed to playbook as "tgtver" is to be a version pattern, not (necessarily) an exact version.
# Version patterns have a letter (e.g. "z") at the end to denote 3rd and (optionally) 4th (dot-separated) version digits of the actual version.
# RedHat satellite-maintain commands will (internally / behind-the-scenes) choose the version to install.
# On version e.g. 6.13.4 replace 3rd (dot-delimited) version digit with e.g. z to allow patch version to be updated.
# Also running `sudo satellite-maintain upgrade list-versions` gives same letter-padded version number:
# ```
# [root@anotherhost# sudo satellite-maintain upgrade list-versions
# Checking for new version of satellite-maintain...
# Nothing to update, can't find new version of satellite-maintain.
# 6.13.z
# ```
# ## Versions available
# 
# For info on versions released / available, go to: https://access.redhat.com/articles/1365633 (Note: may require RH account).
# This page also explains how minor ver changes are called "upgrade", patch version changes an "update".
# 
# ## Version numbering inconsistency in RH Satellite product
# 
# Note also that the version number - in regards to number of digits is inconsistent.
# E.g. Subsequent versions may be numbered 6.13.4 (no fourth digit) and 6.13.4.1 (has 4th digit).
# See: https://access.redhat.com/articles/1365633
# 
# ## Changes
# - Add -y to commands (to prevent interactivity from stopping unattended flow)
# - Enable `when: minorup` tasks for "upgrade (minor version change). This needs more testing.
# - Enable optional reboot task (must issue reboot=1)
# 
# ## References
# https://docs.redhat.com/en/documentation/red_hat_satellite/6.15/html-single/upgrading_connected_red_hat_satellite_to_6.15/index
- name: Upgrade RH Satellite
  hosts: '{{ host }}'
  become: yes
  vars:
    # Note: this could have .z at end (typically for patch version changes, i.e. "updates") - include it
    tgtver: '6.12'
    # Only relevant on minor version change called "upgrade" in RHSat lingo ("minorup == true")
    minorup_repos: ["satellite-maintenance-6.12-for-rhel-8-x86_64-rpms", "satellite-6.12-for-rhel-8-x86_64-rpms"]
    # satellite-maintain upgrade (check, run) default options (shared between two sub-sub commands)
    smup_opts: '--whitelist="check-tmout-variable,non-rh-packages"'
    # Note: Should be FQDN per RH guides. Any satellite install/upgrade flows mess up the hostname.
    # See task below to understand how to fix.
    rhsat_host: 'sat.mycomp.com'
    # Enable "minor" (bigger of 2, see below)
    # Note The bigger upgrade is called "minor upgrade", smaller is called "patch upgrade" (default)
    minorup: 0
    reboot: 0
  tasks:
    - name: Set hostname (to FQDN) for installer
      shell: hostnamectl set-hostname {{ rhsat_host }}
    # manual probe of versions available (e.g.):
    #   satellite-maintain upgrade list-versions
    #   # Suggested: Use health check option (6.11z example uses -w "non-rh-packages")
    #   satellite-maintain upgrade check --target-version 6.12 --health...
    # https://access.redhat.com/solutions/2755731
    - name: Delete Paused tasks
      shell: foreman-rake foreman_tasks:cleanup TASK_SEARCH='label ~ *'  VERBOSE=true STATES='paused,stopped'
    # NEW: Enable "Upgrade" repos (one-by-one for easier Ansible handling)
    - name: Enable minor upgrade version specific Repos
      # Note added enable here to the base command, do multiple repos separately
      # Most of time there is one repo, sometimes two (or more ?). TODO: revamp vars/params
      shell: 'subscription-manager repos --enable {{ item }}'
      #OLD:with_items: veruprepos[tgtver]
      with_items: '{{ minorup_repos }}'
      when: minorup
    - name: Enable Satellite DNF module (for RHEL 8)
      # This seems to be universal across minor upgrades
      shell: 'dnf module enable satellite-maintenance:el8'
      when: minorup
    # This section is common to patch and minor upgrades (always run)
    # For minor version tgtver is someting like "6.14" 
    - name: Check for Upgrade
      shell: satellite-maintain upgrade check -y --target-version {{ tgtver }} --whitelist="check-tmout-variable,non-rh-packages"
    # No --whitelist needed for 6.13 (See vars). Per output this has --force option (to get rid of interactive prompting)
    # Seems -y is effective for suppressing interaction.
    - name: Run Upgrade
      # Seems whitelist opts might depend on version (see verupopts => {{ verupopts[tgtver] }})
      shell: 'satellite-maintain upgrade run -y --target-version {{ tgtver }} --whitelist="check-tmout-variable,non-rh-packages"'
    # At End: Recommended to run: dnf needs-restarting --reboothint
    #
    - name: Advise to fix hostname to RHSat preferred hostname at next reboot
      debug:
        msg: 'Change hostname: hostnamectl set-hostname {{ rhsat_host }}'
    - name: Reboot upgraded host (optional)
      shell: reboot
      when: reboot
