# # Copy remote host SSH user key to central Ansible machine
# Do effective (reverse) ssh-copy-id, except deal with few files
# and text content to avoid password promting interactivity
# during automation (root has rights to do the file shuffle).
# Refs:
# - https://docs.ansible.com/ansible/latest/modules/synchronize_module.html
# Also: lookup('vars', Component) ~ vars[Component]
# hostvars[inventory_hostname][Component]
# lookup('file', 'pubkeys/foo.com.invalid')
# Note: All keys may not be copied on the first run (E.g. 3/5 might be copied) !
# Ansible Concurrency/File synchronization problem (in lineinfile) ?
# All keys were registered properly and showed in debug: output, but only 3/5 ended
# up in file. 2nd run captured the remaining 2 keys.
- name: Copy remote keys to ansible machine
  become: yes
  hosts: '{{ host }}'
  vars:
    # Remote
    remoteuserhome: '/root'
    remotesshdir: '{{ remoteuserhome }}/.ssh'
    localuserhome: '{{ lookup("env","HOME") }}'
    #keyfile: /tmp/foo
    #keyfile: '/root/.ssh/id_rsa'
    keyfile: '{{ remotesshdir }}/id_rsa'
    ahfile: .ssh/authorized_keys
  tasks:
    - name: Check User Remote SSH key presence
      stat:
        path: '{{ keyfile }}'
      register: keystat
    # TODO: generate key if does not exist (-P old, use -N)
    # See -y: print public key to stdout
    - name: Gen Remote Keys (ssh-keygen) whenever missing
      shell: 'ssh-keygen -t rsa -b 4096 -f {{ keyfile }} -N ""'
      when: keystat.stat.exists == False
    #- name: Gen Keys (Ansible:openssh_keypair, > 2.8)
    #  openssh_keypair:
    #    path: /root/.ssh/id_rsa
    #    state: present
    #    type: rsa
    #    size: 4096
    #    force: no
    - name: Extract Remote public key
      #shell: 'cat ~/.ssh/id_rsa.pub'
      shell: 'cat {{ remotesshdir }}/id_rsa.pub'
      register: pubkey
    - debug: msg="Pubkey {{ pubkey.stdout }}"
    - name: Copy Key from Remote to Ansible Host
      lineinfile:
        #content: '{{ pubkey.stdout }}'
        # "line:" adds a newline ? or need "\n"
        line: '{{ pubkey.stdout }}'
        path: '{{ localuserhome }}/{{ ahfile }}'
        state: present
        # TODO: Substring(s) from start and end ?
        # NOTE: Even w/o this re ansible will not insert identical line (!)
        # However if string is even one char off it will.
        #regexp: '^{{ pubkey.stdout }}'
        insertafter: EOF
      delegate_to: localhost
    # Do we need to also add to known_hosts ?
    # https://gist.github.com/shirou/6928012
    - name: Add host to known_hosts    
      # Also -H name,ipaddr
      # shell: 'ssh-keyscan -H {{ inventory_hostname }}' >> ~/.ssh/known_hosts ? Ansible known_hosts ?
      lineinfile:
        dest: '{{ localuserhome }}/.ssh/known_hosts'
        create: yes
        state: present
        # -p' + ansible_ssh_port + ' Need -H 
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa -H ' + inventory_hostname) }}"
      delegate_to: localhost
