- name: Perform ssh-copy-id from localhost
  # Important to *only* be current user
  become: no
  hosts: '{{ host }}'
  # Not fit for authorized_key module?
  connection: local
  #gather_facts: false
  #NOT:serial: 1
  vars:
    remoteuser: 'none'
    remotepass: 'none'
  serial: 50
  tasks:
    - name: SSH Copy id
      # -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      shell: 'sshpass -p {{ remotepass }} ssh-copy-id {{ remoteuser }}@{{ inventory_hostname }}'
      delegate_to: localhost
      #when: inventory_hostname != "local"
      #when:  inventory_hostname  != 'myhost.somewhere.com'
      #when: 0
    - name: SSH Copy id (Easy way)
      authorized_key:
        user: '{{ remoteuser }}'
        state: present
        # Does ~ expand here ?
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: 0
      # Could use (note indent):
      #  key: '{{ item }}'
      # with_file:\n- ~/.ssh/id_rsa.pub
